version: '3.8'

services:
  mysql:
    image: mysql:8.0.35
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: nagaaw
      MYSQL_DATABASE: nagaaw
      MYSQL_USER: nagaaw
      MYSQL_PASSWORD: nagaaw
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - nagaaw_network

volumes:
  mysql_data:

networks:
  nagaaw_network:
